# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd "/epics/ioc"

epicsEnvSet EPICS_TZ GMT0BST

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# simDetectorConfig(portName, maxSizeX, maxSizeY, dataType, maxBuffers, maxMemory)
simDetectorConfig("DET.DET", 1024, 1024, 0, 50, 0)
# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxThreads)
NDStdArraysConfigure("DET.ARR", 2, 0, "DET.DET", 0, 0, 0, 0, 0, 1)

dbLoadRecords /epics/runtime/ioc.db
iocInit


dbpf BL01T-EA-CAM-01:DET:AcquireTime 0.1
dbpf BL01T-EA-CAM-01:ARR:EnableCallbacks 1
dbpf BL01T-EA-CAM-01:DET:Acquire 1

